apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: capstone-eks-cluster
  region: us-east-1
iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::510590228660:role/EKSClusterRole
managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    iam:
      instanceRoleARN: arn:aws:iam::510590228660:instance-profile/EKSWorkerNodeProfile