version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy_green:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/
            kubectl version --client

      - run:
          name: Deploy Green Image
          command: |
            aws eks --region us-east-1 update-kubeconfig --name capstone-eks
            kubectl create deployment green-deploy --image=510590228660.dkr.ecr.us-east-1.amazonaws.com/udacity/capstone:1.0.4 --replicas 1
            kubectl expose deployment/green-deploy --type="LoadBalancer" --port 8080

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_green
