version: 2.1

jobs:
  deploy_green:
    docker:
      - image: circleci/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy Green Image
          command: |
            aws eks --region us-east-1 update-kubeconfig --name capstone-eks
            kubectl create deployment green-deploy --image=510590228660.dkr.ecr.us-east-1.amazonaws.com/udacity/capstone:1.0.4 --replicas 1
            kubectl expose deployment/green-deploy --type="ClusterIP" --port 8080
            # Add any other necessary setup or validation steps

      - run:
          name: Smoke Test Green Deployment
          command: |
            GREEN_SERVICE_IP=$(kubectl get svc green-deploy -o jsonpath='{.spec.clusterIP}')
            curl http://$GREEN_SERVICE_IP:8080
            # Add additional smoke tests as needed


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_green:
