version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  deploy_green:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/
            kubectl version --client
            aws eks --region us-east-1 update-kubeconfig --name capstone-eks

      - run:
          name: Deploy Green Image
          command: |
            kubectl create deployment green-deploy --image=510590228660.dkr.ecr.us-east-1.amazonaws.com/udacity/capstone:1.0.4 --replicas 1
            kubectl expose deployment/green-deploy --type="LoadBalancer" --port 8080
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/
            kubectl version --client
            aws eks --region us-east-1 update-kubeconfig --name capstone-eks
      - run:
          name: Smoke Test Green deployment
          command: |
            GREEN_BASE_URL=$(kubectl get svc green-deploy -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            GREEN_SERVICE_URL="http://${GREEN_SERVICE_URL}:8080/status"
            echo ${GREEN_SERVICE_URL}
            curl -s ${GREEN_SERVICE_URL}
            if curl -s ${GREEN_SERVICE_URL} | grep "OK" 
            then
              echo "Setting success variable for routing switch"
              echo "success=true" >> $BASH_ENV
            else
              echo "Green Deployment smoke test failed"
            fi
            
  switch_routing:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/amd64/kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin/
            kubectl version --client
      - run:
          name: Switch Routing to Green Deployment
          command: |
            echo "$success"
            if [ "$success" == "true" ]; then
                echo "Routing switched to Green Deployment"
              else
                echo "Smoke test failed, not switching routing"
              fi
  

workflows:
  version: 2
  build_and_deploy:
    jobs:
     # - deploy_green
      - smoke_test:
      - switch_routing:
          requires:
            - smoke_test
  