---
version: 2.1
orbs:
    aws-cli: circleci/aws-cli@2.0.3

jobs:
    lint-code:
        docker:
            - image: python:3.8
        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: |
                      make setup
                      make install
                      make hadolint_install
                      pip install awscli
            - run:
                  name: Lint Code
                  command: |
                      make lint
            - run:
                  name: Retrieve Latest Docker TAG from AWS ECR Repo and publish to kvdb
                  command: |
                    latest_version=$(aws ecr describe-images \
                        --region $AWS_DEFAULT_REGION \
                        --repository-name $ECR_REPOSITORY_NAME \
                        --query 'imageDetails|sort_by(@, &imagePushedAt)|[-1].imageTags[0]' \
                        --output text)
                    if [ -z "$latest_version" ]; then
                        latest_version="0.0.0"
                    fi
                    IFS='.' read -r -a version_segments \<<< "$latest_version"
                    last_segment=$((version_segments[2] + 1))
                    new_version="${version_segments[0]}.${version_segments[1]}.$last_segment"
                    echo "Latest Docker image Version: $latest_version"
                    echo "New Docker image version: $new_version"
                    curl --insecure https://kvdb.io/WyZcHsZopDbuuaV2g13iLM/image_${CIRCLE_WORKFLOW_ID:0:7}  -d $new_version
                    echo "New Docker Tag published to kvdb.io"
    build_docker_image:
        docker:
            - image: docker:20.10.6
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Install Dependencies
                  command: |
                    apk add --no-cache python3 py3-pip
                    apk add --no-cache curl
                    ln -sf python3 /usr/bin/python
                    python3 -m ensurepip
                    pip3 install --upgrade pip
                    pip install awscli
            - run:
                  name: Retrieve Latest Docker TAG from AWS ECR Repo and publish to kvdb
                  command: |
                    docker --version
            - run:
                  name: Build Docker image and save it
                  command: |
                    tag=$(curl --insecure https://kvdb.io/WyZcHsZopDbuuaV2g13iLM/image_${CIRCLE_WORKFLOW_ID:0:7})
                    echo "tag : $tag"
                    docker build --tag=$AWS_ACCOUNT_ID$AWS_ECR_DNS/$ECR_REPOSITORY_NAME:$tag .
                    docker save -o /tmp/$ECR_REPOSITORY_NAME:$tag.tar $AWS_ACCOUNT_ID$AWS_ECR_DNS/$ECR_REPOSITORY_NAME:$tag
            - run:
                  name: List Docker image
                  command: |
                    docker images

workflows:
    udacity_capstone:
        jobs:
            - lint-code
            - build_docker_image:
                  requires: [lint-code]
